development:
  consumer_key: tc17jRHgzdGBZ6QCGrQPA
  consumer_secret: LefuOHoGr8IhiphmDMyuYhZwZ6yH1BM4FMonbl02ZeU
production:
  consumer_key: fo8USEblJwCO4xgsTiksg
  consumer_secret: nzSj51nl20aSijRloWy7jTLZF1LXaDhlgPFgJLwrE  